# Generated by Django 3.0.2 on 2020-01-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('host', models.CharField(default='', max_length=255)),
                ('port', models.CharField(default='', max_length=255)),
                ('addr_from', models.CharField(default='', max_length=255)),
                ('addr_to', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
